_MAKE_SWS_(x, _x)
_MAKE_SWS_(y, _y)
_MAKE_SWS_(z, _z)
_MAKE_SWS_(w, _w)
_MAKE_SWS_(xx, _x, _x)
_MAKE_SWS_(yx, _y, _x)
_MAKE_SWS_(zx, _z, _x)
_MAKE_SWS_(wx, _w, _x)
_MAKE_SWS_(xy, _x, _y)
_MAKE_SWS_(yy, _y, _y)
_MAKE_SWS_(zy, _z, _y)
_MAKE_SWS_(wy, _w, _y)
_MAKE_SWS_(xz, _x, _z)
_MAKE_SWS_(yz, _y, _z)
_MAKE_SWS_(zz, _z, _z)
_MAKE_SWS_(wz, _w, _z)
_MAKE_SWS_(xw, _x, _w)
_MAKE_SWS_(yw, _y, _w)
_MAKE_SWS_(zw, _z, _w)
_MAKE_SWS_(ww, _w, _w)
_MAKE_SWS_(xxx, _x, _x, _x)
_MAKE_SWS_(yxx, _y, _x, _x)
_MAKE_SWS_(zxx, _z, _x, _x)
_MAKE_SWS_(wxx, _w, _x, _x)
_MAKE_SWS_(xyx, _x, _y, _x)
_MAKE_SWS_(yyx, _y, _y, _x)
_MAKE_SWS_(zyx, _z, _y, _x)
_MAKE_SWS_(wyx, _w, _y, _x)
_MAKE_SWS_(xzx, _x, _z, _x)
_MAKE_SWS_(yzx, _y, _z, _x)
_MAKE_SWS_(zzx, _z, _z, _x)
_MAKE_SWS_(wzx, _w, _z, _x)
_MAKE_SWS_(xwx, _x, _w, _x)
_MAKE_SWS_(ywx, _y, _w, _x)
_MAKE_SWS_(zwx, _z, _w, _x)
_MAKE_SWS_(wwx, _w, _w, _x)
_MAKE_SWS_(xxy, _x, _x, _y)
_MAKE_SWS_(yxy, _y, _x, _y)
_MAKE_SWS_(zxy, _z, _x, _y)
_MAKE_SWS_(wxy, _w, _x, _y)
_MAKE_SWS_(xyy, _x, _y, _y)
_MAKE_SWS_(yyy, _y, _y, _y)
_MAKE_SWS_(zyy, _z, _y, _y)
_MAKE_SWS_(wyy, _w, _y, _y)
_MAKE_SWS_(xzy, _x, _z, _y)
_MAKE_SWS_(yzy, _y, _z, _y)
_MAKE_SWS_(zzy, _z, _z, _y)
_MAKE_SWS_(wzy, _w, _z, _y)
_MAKE_SWS_(xwy, _x, _w, _y)
_MAKE_SWS_(ywy, _y, _w, _y)
_MAKE_SWS_(zwy, _z, _w, _y)
_MAKE_SWS_(wwy, _w, _w, _y)
_MAKE_SWS_(xxz, _x, _x, _z)
_MAKE_SWS_(yxz, _y, _x, _z)
_MAKE_SWS_(zxz, _z, _x, _z)
_MAKE_SWS_(wxz, _w, _x, _z)
_MAKE_SWS_(xyz, _x, _y, _z)
_MAKE_SWS_(yyz, _y, _y, _z)
_MAKE_SWS_(zyz, _z, _y, _z)
_MAKE_SWS_(wyz, _w, _y, _z)
_MAKE_SWS_(xzz, _x, _z, _z)
_MAKE_SWS_(yzz, _y, _z, _z)
_MAKE_SWS_(zzz, _z, _z, _z)
_MAKE_SWS_(wzz, _w, _z, _z)
_MAKE_SWS_(xwz, _x, _w, _z)
_MAKE_SWS_(ywz, _y, _w, _z)
_MAKE_SWS_(zwz, _z, _w, _z)
_MAKE_SWS_(wwz, _w, _w, _z)
_MAKE_SWS_(xxw, _x, _x, _w)
_MAKE_SWS_(yxw, _y, _x, _w)
_MAKE_SWS_(zxw, _z, _x, _w)
_MAKE_SWS_(wxw, _w, _x, _w)
_MAKE_SWS_(xyw, _x, _y, _w)
_MAKE_SWS_(yyw, _y, _y, _w)
_MAKE_SWS_(zyw, _z, _y, _w)
_MAKE_SWS_(wyw, _w, _y, _w)
_MAKE_SWS_(xzw, _x, _z, _w)
_MAKE_SWS_(yzw, _y, _z, _w)
_MAKE_SWS_(zzw, _z, _z, _w)
_MAKE_SWS_(wzw, _w, _z, _w)
_MAKE_SWS_(xww, _x, _w, _w)
_MAKE_SWS_(yww, _y, _w, _w)
_MAKE_SWS_(zww, _z, _w, _w)
_MAKE_SWS_(www, _w, _w, _w)
_MAKE_SWS_(xxxx, _x, _x, _x, _x)
_MAKE_SWS_(yxxx, _y, _x, _x, _x)
_MAKE_SWS_(zxxx, _z, _x, _x, _x)
_MAKE_SWS_(wxxx, _w, _x, _x, _x)
_MAKE_SWS_(xyxx, _x, _y, _x, _x)
_MAKE_SWS_(yyxx, _y, _y, _x, _x)
_MAKE_SWS_(zyxx, _z, _y, _x, _x)
_MAKE_SWS_(wyxx, _w, _y, _x, _x)
_MAKE_SWS_(xzxx, _x, _z, _x, _x)
_MAKE_SWS_(yzxx, _y, _z, _x, _x)
_MAKE_SWS_(zzxx, _z, _z, _x, _x)
_MAKE_SWS_(wzxx, _w, _z, _x, _x)
_MAKE_SWS_(xwxx, _x, _w, _x, _x)
_MAKE_SWS_(ywxx, _y, _w, _x, _x)
_MAKE_SWS_(zwxx, _z, _w, _x, _x)
_MAKE_SWS_(wwxx, _w, _w, _x, _x)
_MAKE_SWS_(xxyx, _x, _x, _y, _x)
_MAKE_SWS_(yxyx, _y, _x, _y, _x)
_MAKE_SWS_(zxyx, _z, _x, _y, _x)
_MAKE_SWS_(wxyx, _w, _x, _y, _x)
_MAKE_SWS_(xyyx, _x, _y, _y, _x)
_MAKE_SWS_(yyyx, _y, _y, _y, _x)
_MAKE_SWS_(zyyx, _z, _y, _y, _x)
_MAKE_SWS_(wyyx, _w, _y, _y, _x)
_MAKE_SWS_(xzyx, _x, _z, _y, _x)
_MAKE_SWS_(yzyx, _y, _z, _y, _x)
_MAKE_SWS_(zzyx, _z, _z, _y, _x)
_MAKE_SWS_(wzyx, _w, _z, _y, _x)
_MAKE_SWS_(xwyx, _x, _w, _y, _x)
_MAKE_SWS_(ywyx, _y, _w, _y, _x)
_MAKE_SWS_(zwyx, _z, _w, _y, _x)
_MAKE_SWS_(wwyx, _w, _w, _y, _x)
_MAKE_SWS_(xxzx, _x, _x, _z, _x)
_MAKE_SWS_(yxzx, _y, _x, _z, _x)
_MAKE_SWS_(zxzx, _z, _x, _z, _x)
_MAKE_SWS_(wxzx, _w, _x, _z, _x)
_MAKE_SWS_(xyzx, _x, _y, _z, _x)
_MAKE_SWS_(yyzx, _y, _y, _z, _x)
_MAKE_SWS_(zyzx, _z, _y, _z, _x)
_MAKE_SWS_(wyzx, _w, _y, _z, _x)
_MAKE_SWS_(xzzx, _x, _z, _z, _x)
_MAKE_SWS_(yzzx, _y, _z, _z, _x)
_MAKE_SWS_(zzzx, _z, _z, _z, _x)
_MAKE_SWS_(wzzx, _w, _z, _z, _x)
_MAKE_SWS_(xwzx, _x, _w, _z, _x)
_MAKE_SWS_(ywzx, _y, _w, _z, _x)
_MAKE_SWS_(zwzx, _z, _w, _z, _x)
_MAKE_SWS_(wwzx, _w, _w, _z, _x)
_MAKE_SWS_(xxwx, _x, _x, _w, _x)
_MAKE_SWS_(yxwx, _y, _x, _w, _x)
_MAKE_SWS_(zxwx, _z, _x, _w, _x)
_MAKE_SWS_(wxwx, _w, _x, _w, _x)
_MAKE_SWS_(xywx, _x, _y, _w, _x)
_MAKE_SWS_(yywx, _y, _y, _w, _x)
_MAKE_SWS_(zywx, _z, _y, _w, _x)
_MAKE_SWS_(wywx, _w, _y, _w, _x)
_MAKE_SWS_(xzwx, _x, _z, _w, _x)
_MAKE_SWS_(yzwx, _y, _z, _w, _x)
_MAKE_SWS_(zzwx, _z, _z, _w, _x)
_MAKE_SWS_(wzwx, _w, _z, _w, _x)
_MAKE_SWS_(xwwx, _x, _w, _w, _x)
_MAKE_SWS_(ywwx, _y, _w, _w, _x)
_MAKE_SWS_(zwwx, _z, _w, _w, _x)
_MAKE_SWS_(wwwx, _w, _w, _w, _x)
_MAKE_SWS_(xxxy, _x, _x, _x, _y)
_MAKE_SWS_(yxxy, _y, _x, _x, _y)
_MAKE_SWS_(zxxy, _z, _x, _x, _y)
_MAKE_SWS_(wxxy, _w, _x, _x, _y)
_MAKE_SWS_(xyxy, _x, _y, _x, _y)
_MAKE_SWS_(yyxy, _y, _y, _x, _y)
_MAKE_SWS_(zyxy, _z, _y, _x, _y)
_MAKE_SWS_(wyxy, _w, _y, _x, _y)
_MAKE_SWS_(xzxy, _x, _z, _x, _y)
_MAKE_SWS_(yzxy, _y, _z, _x, _y)
_MAKE_SWS_(zzxy, _z, _z, _x, _y)
_MAKE_SWS_(wzxy, _w, _z, _x, _y)
_MAKE_SWS_(xwxy, _x, _w, _x, _y)
_MAKE_SWS_(ywxy, _y, _w, _x, _y)
_MAKE_SWS_(zwxy, _z, _w, _x, _y)
_MAKE_SWS_(wwxy, _w, _w, _x, _y)
_MAKE_SWS_(xxyy, _x, _x, _y, _y)
_MAKE_SWS_(yxyy, _y, _x, _y, _y)
_MAKE_SWS_(zxyy, _z, _x, _y, _y)
_MAKE_SWS_(wxyy, _w, _x, _y, _y)
_MAKE_SWS_(xyyy, _x, _y, _y, _y)
_MAKE_SWS_(yyyy, _y, _y, _y, _y)
_MAKE_SWS_(zyyy, _z, _y, _y, _y)
_MAKE_SWS_(wyyy, _w, _y, _y, _y)
_MAKE_SWS_(xzyy, _x, _z, _y, _y)
_MAKE_SWS_(yzyy, _y, _z, _y, _y)
_MAKE_SWS_(zzyy, _z, _z, _y, _y)
_MAKE_SWS_(wzyy, _w, _z, _y, _y)
_MAKE_SWS_(xwyy, _x, _w, _y, _y)
_MAKE_SWS_(ywyy, _y, _w, _y, _y)
_MAKE_SWS_(zwyy, _z, _w, _y, _y)
_MAKE_SWS_(wwyy, _w, _w, _y, _y)
_MAKE_SWS_(xxzy, _x, _x, _z, _y)
_MAKE_SWS_(yxzy, _y, _x, _z, _y)
_MAKE_SWS_(zxzy, _z, _x, _z, _y)
_MAKE_SWS_(wxzy, _w, _x, _z, _y)
_MAKE_SWS_(xyzy, _x, _y, _z, _y)
_MAKE_SWS_(yyzy, _y, _y, _z, _y)
_MAKE_SWS_(zyzy, _z, _y, _z, _y)
_MAKE_SWS_(wyzy, _w, _y, _z, _y)
_MAKE_SWS_(xzzy, _x, _z, _z, _y)
_MAKE_SWS_(yzzy, _y, _z, _z, _y)
_MAKE_SWS_(zzzy, _z, _z, _z, _y)
_MAKE_SWS_(wzzy, _w, _z, _z, _y)
_MAKE_SWS_(xwzy, _x, _w, _z, _y)
_MAKE_SWS_(ywzy, _y, _w, _z, _y)
_MAKE_SWS_(zwzy, _z, _w, _z, _y)
_MAKE_SWS_(wwzy, _w, _w, _z, _y)
_MAKE_SWS_(xxwy, _x, _x, _w, _y)
_MAKE_SWS_(yxwy, _y, _x, _w, _y)
_MAKE_SWS_(zxwy, _z, _x, _w, _y)
_MAKE_SWS_(wxwy, _w, _x, _w, _y)
_MAKE_SWS_(xywy, _x, _y, _w, _y)
_MAKE_SWS_(yywy, _y, _y, _w, _y)
_MAKE_SWS_(zywy, _z, _y, _w, _y)
_MAKE_SWS_(wywy, _w, _y, _w, _y)
_MAKE_SWS_(xzwy, _x, _z, _w, _y)
_MAKE_SWS_(yzwy, _y, _z, _w, _y)
_MAKE_SWS_(zzwy, _z, _z, _w, _y)
_MAKE_SWS_(wzwy, _w, _z, _w, _y)
_MAKE_SWS_(xwwy, _x, _w, _w, _y)
_MAKE_SWS_(ywwy, _y, _w, _w, _y)
_MAKE_SWS_(zwwy, _z, _w, _w, _y)
_MAKE_SWS_(wwwy, _w, _w, _w, _y)
_MAKE_SWS_(xxxz, _x, _x, _x, _z)
_MAKE_SWS_(yxxz, _y, _x, _x, _z)
_MAKE_SWS_(zxxz, _z, _x, _x, _z)
_MAKE_SWS_(wxxz, _w, _x, _x, _z)
_MAKE_SWS_(xyxz, _x, _y, _x, _z)
_MAKE_SWS_(yyxz, _y, _y, _x, _z)
_MAKE_SWS_(zyxz, _z, _y, _x, _z)
_MAKE_SWS_(wyxz, _w, _y, _x, _z)
_MAKE_SWS_(xzxz, _x, _z, _x, _z)
_MAKE_SWS_(yzxz, _y, _z, _x, _z)
_MAKE_SWS_(zzxz, _z, _z, _x, _z)
_MAKE_SWS_(wzxz, _w, _z, _x, _z)
_MAKE_SWS_(xwxz, _x, _w, _x, _z)
_MAKE_SWS_(ywxz, _y, _w, _x, _z)
_MAKE_SWS_(zwxz, _z, _w, _x, _z)
_MAKE_SWS_(wwxz, _w, _w, _x, _z)
_MAKE_SWS_(xxyz, _x, _x, _y, _z)
_MAKE_SWS_(yxyz, _y, _x, _y, _z)
_MAKE_SWS_(zxyz, _z, _x, _y, _z)
_MAKE_SWS_(wxyz, _w, _x, _y, _z)
_MAKE_SWS_(xyyz, _x, _y, _y, _z)
_MAKE_SWS_(yyyz, _y, _y, _y, _z)
_MAKE_SWS_(zyyz, _z, _y, _y, _z)
_MAKE_SWS_(wyyz, _w, _y, _y, _z)
_MAKE_SWS_(xzyz, _x, _z, _y, _z)
_MAKE_SWS_(yzyz, _y, _z, _y, _z)
_MAKE_SWS_(zzyz, _z, _z, _y, _z)
_MAKE_SWS_(wzyz, _w, _z, _y, _z)
_MAKE_SWS_(xwyz, _x, _w, _y, _z)
_MAKE_SWS_(ywyz, _y, _w, _y, _z)
_MAKE_SWS_(zwyz, _z, _w, _y, _z)
_MAKE_SWS_(wwyz, _w, _w, _y, _z)
_MAKE_SWS_(xxzz, _x, _x, _z, _z)
_MAKE_SWS_(yxzz, _y, _x, _z, _z)
_MAKE_SWS_(zxzz, _z, _x, _z, _z)
_MAKE_SWS_(wxzz, _w, _x, _z, _z)
_MAKE_SWS_(xyzz, _x, _y, _z, _z)
_MAKE_SWS_(yyzz, _y, _y, _z, _z)
_MAKE_SWS_(zyzz, _z, _y, _z, _z)
_MAKE_SWS_(wyzz, _w, _y, _z, _z)
_MAKE_SWS_(xzzz, _x, _z, _z, _z)
_MAKE_SWS_(yzzz, _y, _z, _z, _z)
_MAKE_SWS_(zzzz, _z, _z, _z, _z)
_MAKE_SWS_(wzzz, _w, _z, _z, _z)
_MAKE_SWS_(xwzz, _x, _w, _z, _z)
_MAKE_SWS_(ywzz, _y, _w, _z, _z)
_MAKE_SWS_(zwzz, _z, _w, _z, _z)
_MAKE_SWS_(wwzz, _w, _w, _z, _z)
_MAKE_SWS_(xxwz, _x, _x, _w, _z)
_MAKE_SWS_(yxwz, _y, _x, _w, _z)
_MAKE_SWS_(zxwz, _z, _x, _w, _z)
_MAKE_SWS_(wxwz, _w, _x, _w, _z)
_MAKE_SWS_(xywz, _x, _y, _w, _z)
_MAKE_SWS_(yywz, _y, _y, _w, _z)
_MAKE_SWS_(zywz, _z, _y, _w, _z)
_MAKE_SWS_(wywz, _w, _y, _w, _z)
_MAKE_SWS_(xzwz, _x, _z, _w, _z)
_MAKE_SWS_(yzwz, _y, _z, _w, _z)
_MAKE_SWS_(zzwz, _z, _z, _w, _z)
_MAKE_SWS_(wzwz, _w, _z, _w, _z)
_MAKE_SWS_(xwwz, _x, _w, _w, _z)
_MAKE_SWS_(ywwz, _y, _w, _w, _z)
_MAKE_SWS_(zwwz, _z, _w, _w, _z)
_MAKE_SWS_(wwwz, _w, _w, _w, _z)
_MAKE_SWS_(xxxw, _x, _x, _x, _w)
_MAKE_SWS_(yxxw, _y, _x, _x, _w)
_MAKE_SWS_(zxxw, _z, _x, _x, _w)
_MAKE_SWS_(wxxw, _w, _x, _x, _w)
_MAKE_SWS_(xyxw, _x, _y, _x, _w)
_MAKE_SWS_(yyxw, _y, _y, _x, _w)
_MAKE_SWS_(zyxw, _z, _y, _x, _w)
_MAKE_SWS_(wyxw, _w, _y, _x, _w)
_MAKE_SWS_(xzxw, _x, _z, _x, _w)
_MAKE_SWS_(yzxw, _y, _z, _x, _w)
_MAKE_SWS_(zzxw, _z, _z, _x, _w)
_MAKE_SWS_(wzxw, _w, _z, _x, _w)
_MAKE_SWS_(xwxw, _x, _w, _x, _w)
_MAKE_SWS_(ywxw, _y, _w, _x, _w)
_MAKE_SWS_(zwxw, _z, _w, _x, _w)
_MAKE_SWS_(wwxw, _w, _w, _x, _w)
_MAKE_SWS_(xxyw, _x, _x, _y, _w)
_MAKE_SWS_(yxyw, _y, _x, _y, _w)
_MAKE_SWS_(zxyw, _z, _x, _y, _w)
_MAKE_SWS_(wxyw, _w, _x, _y, _w)
_MAKE_SWS_(xyyw, _x, _y, _y, _w)
_MAKE_SWS_(yyyw, _y, _y, _y, _w)
_MAKE_SWS_(zyyw, _z, _y, _y, _w)
_MAKE_SWS_(wyyw, _w, _y, _y, _w)
_MAKE_SWS_(xzyw, _x, _z, _y, _w)
_MAKE_SWS_(yzyw, _y, _z, _y, _w)
_MAKE_SWS_(zzyw, _z, _z, _y, _w)
_MAKE_SWS_(wzyw, _w, _z, _y, _w)
_MAKE_SWS_(xwyw, _x, _w, _y, _w)
_MAKE_SWS_(ywyw, _y, _w, _y, _w)
_MAKE_SWS_(zwyw, _z, _w, _y, _w)
_MAKE_SWS_(wwyw, _w, _w, _y, _w)
_MAKE_SWS_(xxzw, _x, _x, _z, _w)
_MAKE_SWS_(yxzw, _y, _x, _z, _w)
_MAKE_SWS_(zxzw, _z, _x, _z, _w)
_MAKE_SWS_(wxzw, _w, _x, _z, _w)
_MAKE_SWS_(xyzw, _x, _y, _z, _w)
_MAKE_SWS_(yyzw, _y, _y, _z, _w)
_MAKE_SWS_(zyzw, _z, _y, _z, _w)
_MAKE_SWS_(wyzw, _w, _y, _z, _w)
_MAKE_SWS_(xzzw, _x, _z, _z, _w)
_MAKE_SWS_(yzzw, _y, _z, _z, _w)
_MAKE_SWS_(zzzw, _z, _z, _z, _w)
_MAKE_SWS_(wzzw, _w, _z, _z, _w)
_MAKE_SWS_(xwzw, _x, _w, _z, _w)
_MAKE_SWS_(ywzw, _y, _w, _z, _w)
_MAKE_SWS_(zwzw, _z, _w, _z, _w)
_MAKE_SWS_(wwzw, _w, _w, _z, _w)
_MAKE_SWS_(xxww, _x, _x, _w, _w)
_MAKE_SWS_(yxww, _y, _x, _w, _w)
_MAKE_SWS_(zxww, _z, _x, _w, _w)
_MAKE_SWS_(wxww, _w, _x, _w, _w)
_MAKE_SWS_(xyww, _x, _y, _w, _w)
_MAKE_SWS_(yyww, _y, _y, _w, _w)
_MAKE_SWS_(zyww, _z, _y, _w, _w)
_MAKE_SWS_(wyww, _w, _y, _w, _w)
_MAKE_SWS_(xzww, _x, _z, _w, _w)
_MAKE_SWS_(yzww, _y, _z, _w, _w)
_MAKE_SWS_(zzww, _z, _z, _w, _w)
_MAKE_SWS_(wzww, _w, _z, _w, _w)
_MAKE_SWS_(xwww, _x, _w, _w, _w)
_MAKE_SWS_(ywww, _y, _w, _w, _w)
_MAKE_SWS_(zwww, _z, _w, _w, _w)
_MAKE_SWS_(wwww, _w, _w, _w, _w)
